### ISSUE TITLE
Needs reCaptcha v2 update

### ISSUE THREAD

**Issue by magentatech** [shivprakash210/wp-service-payment-form-with-authorizenet#1]
reCaptcha v1 is no longer working.  Can you update?

**Comment by mrpink84** [comment]
I second this! Please update to reCaptcha v2 or v3 or at least let us bypass reCaptcha (Maybe add a simple quiz option?) Thanks!!!!

**Comment by shivprakash210** [comment]
> reCaptcha v1 is no longer working. Can you update?



> I second this! Please update to reCaptcha v2 or v3 or at least let us bypass reCaptcha (Maybe add a simple quiz option?) Thanks!!!!

Sure, I will update it ASAP

**Comment by magentatech** [comment]
Shiv, I saw you published a new version of the plugin on wordpress.  Does that implement the new reCaptcha v2 / v3?   Hoping you can republish here as well.  If not, I can get it from the plugin files.  (I have it customized further, but not enough to branch)

**Comment by shivprakash210** [comment]
@magentatech and @mrpink84 , This plugin is updated now with reCaptcha v2.

Thanks
