### ISSUE TITLE
Can't Delete Entries (No Bulk Actions)

### ISSUE THREAD

**Issue by jimcutler** [shivprakash210/wp-service-payment-form-with-authorizenet#10]
The All Payments table in Service Payment admin has no ability to delete entries.

**Comment by shivprakash210** [comment]
I will add this feature ASAP.

**Comment by jimcutler** [comment]
I have a fix for this in my forked branch that just needs testing. When it's ready I'll send you a PR.

**Comment by shivprakash210** [comment]
Thanks
