### ISSUE TITLE
Will this work with Wordpress 5.7.1?

### ISSUE THREAD

**Issue by apdvrjn** [shivprakash210/wp-service-payment-form-with-authorizenet#16]
More of a question than an issue. Will this plugin work with Wordpress version 5.7.1? I see that it hasn't been tested on that version.
<img width="758" alt="Screen Shot 2021-04-22 at 14 05 59" src="https://user-images.githubusercontent.com/82917718/115771680-e0062e00-a373-11eb-94de-77d0adca982e.png">

**Comment by apdvrjn** [comment]
Looks like it works but I received this error even though the ID's are correct. 


<img width="1053" alt="Screen Shot 2021-04-22 at 14 49 12" src="https://user-images.githubusercontent.com/82917718/115776874-3c6c4c00-a37a-11eb-873b-9716ec18b5dc.png">

**Comment by apdvrjn** [comment]
I tried in production and received the same error. Spoke to authorize.net and confirmed that API ID and transaction key are correct. Could it be the URL that the gateway is being posted to?  I was told it should be one of the below based on the service being used:


<img width="1240" alt="Screen Shot 2021-04-22 at 15 34 58" src="https://user-images.githubusercontent.com/82917718/115781683-4db85700-a380-11eb-8cae-3de1349f2583.png">


Thanks for your help!

**Comment by shivprakash210** [comment]
Plugin tested with latest version of wp (5.8)
