### ISSUE TITLE
Does this plug-in work with newer versions of WordPress?

### ISSUE THREAD

**Issue by blbennett321** [shivprakash210/wp-service-payment-form-with-authorizenet#17]
I noticed a question from April 22, 2021 that was not responded to. Does this plugin work with the newest releases of WordPress? Also, I see that there is the potential for ACH processing. Does the code that's in the link for accepting checks have to be added to a particular WordPress file or is it already included in the downloadable plugin?

Thanks,
Bill

**Comment by shivprakash210** [comment]
plugin tested with latest version (5.8) of wordpress.
