### ISSUE TITLE
WP Service Payment Form With Authorize.net plugin cannot be deleted

### ISSUE THREAD

**Issue by gabrielhill** [shivprakash210/wp-service-payment-form-with-authorizenet#19]
Installed the "WP Service Payment Form With Authorize.net" plugin on my Wordpress site running version 5.8, then tried to delete the plugin, but it keeps giving me this error:

"Deletion failed: The link you followed has expired. Please try again."

**Comment by shivprakash210** [comment]
Yes, this issue is known issue and I am updating plugin. I hope I will completed it very soon.

**Comment by gabrielhill** [comment]
I saw someone else reported this issue to you over 1 year and 2 months ago and you have not resolved the issue in all this time. 
I've manually deleted the plugin folder.

**Comment by shivprakash210** [comment]
Yes, you are correct. I am super busy in one of my super high priority project. I hope, it will complete very soon then I will focus on this plugin update.
For now please delete it manually.

Thanks

**Comment by shivprakash210** [comment]
Plugin delete issue fixed.
