### ISSUE TITLE
Updating failed. Error message: The response is not a valid JSON response.

### ISSUE THREAD

**Issue by friekman** [shivprakash210/wp-service-payment-form-with-authorizenet#2]
On the latest WordPress with the latest version of PHP/MySQL the top of the page says:

"Updating failed. Error message: The response is not a valid JSON response."
![FireShot Capture 082 - Add New Page ‹ William J  Shea, CPA — WordPress - williamjsheacpa com](https://user-images.githubusercontent.com/2123423/69070365-047b0f80-09f6-11ea-85b3-5a240a46e976.jpg)

**Comment by shivprakash210** [comment]
@friekman , I am working on this issue and I will the repository when I will fix this issue.
If you need it urgent fix then please connect with me skype "shiv.prakash76"
Thanks

**Comment by friekman** [comment]
Hi Shiv,

Thank you. I am happy to wait. If it is any help, I installed a plugin that
creates https. I can give you more environment information. Please let me
know.

Best,
Marc

**Comment by shivprakash210** [comment]
Thanks,  I will update when I will fix it.

**Comment by shivprakash210** [comment]
Hi @friekman ,

I have fixed this issue. Please install updated version of plugin.
